---
title: "INCASI Pilot analysis"
author: "Michael Gaebler"
date: "12 Oktober 2016"
output: html_document
---

```{r setup, include=FALSE}
require(R.matlab)
require(circular)

# set working directory
workdir <- 'C:/Users/michael/Documents/INCASI/20161007_LabtestData'
#setwd('D:/INCASI/Labtest/20171007') 
```

# import logfile 

```{r log}

# read logfile
log <- read.csv(file.path(workdir,'inc1mert.dat'), sep = '\t') 

# name columns of logfile
colnames(log) <- c('block', 'trialnum', 'stimnum', 'oldnew', 'valence', 'dummy1', 'fixonset', 
                   'piconset', 'picoffset', 'clickonset', 'dummy2', 'rateonset', 'dummy3', 'dummy4', 'rightwrong')

# read markers of stimulation (using R.matlab package)
matinfo <- readMat(file.path(workdir,'inc1mert.mat'))

# check length between markers
logonset_s <- as.numeric(matinfo$const[3])
logoffset_s <- as.numeric(matinfo$const[4])

logduration_s <- logoffset_s - logonset_s 

```

# import ECG file

```{r ecg}

# specify ECG sampling frequency (in Hz)
ecg_sf <-  2048 # --> 1 datapoint every 0.4882812 ms (1000/2048)

# import raw data
ecg <- read.csv(file.path(workdir,'Testdaten_EXG1und2.csv'), sep = '\t')

# import markers from ECG file ("events")
ecg_events <- read.csv(file.path(workdir,'Testdaten_EXG1und2_events.csv'), sep = '\t')

# check length between markers
ecgonset_s <- ecg_events[1,3] / ecg_sf
ecgoffset_s <- ecg_events[2,3] / ecg_sf

ecgduration_s <- (ecg_events[2,3] - ecg_events[1,3]) / ecg_sf

```

## quality checks
```{r qc}

# deviation between ECG and logfile length between markers (in s)
deviation_s <- abs(ecgduration_s - logduration_s)
print(deviation_s)

# check pic duration
log$pic_duration <- log$picoffset - log$piconset
print(log$pic_duration)

```

## peaks (with Kubios)
```{r pks}


# exg1_crop <- ecg$EXG1[ecg_events[1,3]:length(ecg$EXG1)]
# exg2_crop <- ecg$EXG2[ecg_events[1,3]:length(ecg$EXG2)]

#exg1_crop_resamp <- resample(exg1_crop, 1000, 2048) # get resample() from signal

# write.csv(exg1_crop, 'EXG1_cropped_4Kubios.csv')
# write.csv(exg2_crop, 'EXG2_cropped_4Kubios.csv')

exg2_peaks_tmp <- readMat(file.path(workdir,'EXG2_cropped_4Kubios_hrv.mat'))
exg2_peaks <- as.vector(exg2_peaks_tmp$Res[[4]][[2]][[2]]) # read timepoints of R-peaks Kubios output directly into R


#exg1_peaks <- read.csv(file.path(workdir,'EXG1_cropped_4Kubios.csv'))
#exg2_peaks <- read.csv(file.path(workdir,'EXG2_cropped_4Kubios.csv'))

#exg1_peaks <- as.vector(exg1_peaks[,1])
#exg2_peaks <- as.vector(exg2_peaks[,1])

```

## analyse encoding section
```{r enc}


diff_ecg_log <- ecgonset_s 
log$clickonset_ecgtime_s <- (log$clickonset/1000 - logonset_s) 
log$clickonset_ecgtime_dpt <- log$clickonset_ecgtime_s * ecg_sf

log_encode <- subset(log, log$block == 1)

for (ipt in 1:length(log_encode$clickonset_ecgtime_s)) {
  

position <-  max(which(exg2_peaks < log_encode$clickonset_ecgtime_s[ipt])) # what's the time of the peak just before the click

log_encode$diff_click_peak_ms[ipt] <- (log_encode$clickonset_ecgtime_s[ipt] - exg2_peaks[position]) * 1000 
  
#  log_encode$clickonset_ecgtime_s[ipt] - exg2_peaks[position]
#  log_encode$clickonset_ecgtime_s[ipt] - exg2_peaks[position+1]
  
log_encode$frq_Hz[ipt] <- 60 / (exg2_peaks[position+1] - exg2_peaks[position])


# transform into rad: 2 * pi * frequency * time (in ms)
log_encode$rad[ipt] <- (2 * pi * log_encode$frq_Hz[ipt] * log_encode$diff_click_peak_ms[ipt]) / 1000
  
  
}

```

```{r plotenc1}



hist(log_encode$rad, 20, main = "Histogram of clicks relative to cardiac phase", xlab = "cardiac phase (rad)")

# plot in circular plot 

H = circular(log_encode$rad, type="angle", units="radians", rotation="clock", zero=pi/2)

# plot(H)

# circ.dens = density(H+3*pi/2, bw=bw.nrd0(H))
circ.dens = density(H, bw=bw.nrd0(H))

```

```{r plotenc2, fig.width=5, fig.height=5.5}

plot(H, stack=TRUE, main = "Clicks relative to cardiac phase")
lines(circ.dens, col="darkgrey", lwd = 3, xpd=TRUE)


# QUESTION (@Sven): how to estimate circular density? --> https://www.r-bloggers.com/circular-or-spherical-data-and-density-estimation/

# circ.dens = density(H,bw=20) # estimate circular density (does that make sense?)
# lines(circ.dens, col="darkgrey", lwd=3)

```